version: '3.9'

services:
  # Microserviço Cliente ----------------------------------------------------------------------
  cliente_db:
    image: postgres:latest
    container_name: cliente_db
    networks:
      - infra_network
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: cliente_user
      POSTGRES_PASSWORD: cliente_pass
    ports:
      - "5433:5432"
    volumes:
      - ./data/cliente_db:/var/lib/postgresql/data

  flyway_cliente:
    image: flyway/flyway:latest
    container_name: flyway_cliente
    command: -url=jdbc:postgresql://cliente_db:5432/clientedb -schemas=public -user=cliente_user -password=cliente_pass migrate
    depends_on:
      - cliente_db
    volumes:
      - ./flyway/sql/cliente:/flyway/sql
    networks:
      - infra_network

  # Microserviço Produto ----------------------------------------------------------------------
  produto_db:
    image: postgres:latest
    container_name: produto_db
    networks:
      - infra_network
    environment:
      POSTGRES_DB: produtodb
      POSTGRES_USER: produto_user
      POSTGRES_PASSWORD: produto_pass
    ports:
      - "5434:5432"
    volumes:
      - ./data/produto_db:/var/lib/postgresql/data

  flyway_produto:
    image: flyway/flyway:latest
    container_name: flyway_produto
    command: -url=jdbc:postgresql://produto_db:5432/produtodb -schemas=public -user=produto_user -password=produto_pass migrate
    depends_on:
      - produto_db
    volumes:
      - ./flyway/sql/produto:/flyway/sql
    networks:
      - infra_network

  # Microserviço Estoque ----------------------------------------------------------------------
  estoque_db:
    image: postgres:latest
    container_name: estoque_db
    networks:
      - infra_network
    environment:
      POSTGRES_DB: estoquedb
      POSTGRES_USER: estoque_user
      POSTGRES_PASSWORD: estoque_pass
    ports:
      - "5435:5432"
    volumes:
      - ./data/estoque_db:/var/lib/postgresql/data

  flyway_estoque:
    image: flyway/flyway:latest
    container_name: flyway_estoque
    command: -url=jdbc:postgresql://estoque_db:5432/estoquedb -schemas=public -user=estoque_user -password=estoque_pass migrate
    depends_on:
      - estoque_db
    volumes:
      - ./flyway/sql/estoque:/flyway/sql
    networks:
      - infra_network

# Rede ----------------------------------------------------------------------
networks:
  infra_network:
    driver: bridge
