version: '3.9'

services:
  gerenciamento:
    image: postgres:latest
    container_name: gerenciamento
    restart: always
    environment:
      POSTGRES_USER: gerenciamento_user
      POSTGRES_PASSWORD: gerenciamento_pass
      POSTGRES_DB: gerenciamentodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - infra_network

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrations
    depends_on:
      - gerenciamento
    command: -url=jdbc:postgresql://gerenciamento:5432/gerenciamentodb -user=gerenciamento_user -password=gerenciamento_pass -locations=filesystem:/migrations -baselineOnMigrate=true migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - infra_network

volumes:
  postgres_data:

# REDE
networks:
  infra_network:
    driver: bridge