version: '3.9'

services:
  # Microserviço Cliente ----------------------------------------------------------------------
  cliente_db:
    image: postgres:latest
    container_name: cliente_db
    networks:
      - infra_network
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: cliente_user
      POSTGRES_PASSWORD: cliente_pass
    ports:
      - "5433:5432"
    volumes:
      - ./data/cliente_db:/var/lib/postgresql/data

  flyway_cliente:
    image: flyway/flyway:latest
    container_name: flyway
    command: -url=jdbc:postgresql://cliente_db:5432/clientedb -schemas=public -user=cliente_user -password=cliente_pass migrate
    depends_on:
      - cliente_db
    volumes:
      - ./flyway/sql:/flyway/sql
    networks:
      - infra_network  # Corrigido para a rede correta

  # Microserviço Produto ----------------------------------------------------------------------
  produto_db:
    image: postgres:latest
    container_name: produto_db
    networks:
      - infra_network
    environment:
      POSTGRES_DB: produtodb
      POSTGRES_USER: produto_user
      POSTGRES_PASSWORD: produto_pass
    ports:
      - "5434:5432"
    volumes:
      - ./data/produto_db:/var/lib/postgresql/data

# Rede ----------------------------------------------------------------------
networks:
  infra_network:
    driver: bridge
